# Generated by Django 3.2.25 on 2025-05-26 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_auto_20250526_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='sparepart',
            name='spare_part_type',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('admin', 'Администратор'), ('master', 'Мастер'), ('client', 'Клиент')], default='client', max_length=20, verbose_name='Роль пользователя'),
        ),
        migrations.DeleteModel(
            name='ServiceType',
        ),
        migrations.DeleteModel(
            name='SparePartType',
        ),
    ]
