# Generated by Django 3.2.25 on 2025-05-26 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_auto_20250526_2155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Купон')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Сумма скидки')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Промокод')),
                ('discount', models.PositiveIntegerField(verbose_name='Скидка в процентах')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
            ],
        ),
    ]
