# Generated by Django 3.2.25 on 2025-05-26 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0006_coupon_promocode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='master',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='master', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
